### ISSUE TITLE
Passing columnFilterProps to SubHeader yields an Error

### ISSUE THREAD

**Issue by sudharsanbb** [bigbinary/neeto-ui#303]
For the SubHeader Component I am getting an error when I pass columnFilterProps like below:

**<SubHeader
      searchProps={{
        value: searchTerm,
        onChange: e => setSearchTerm(e.target.value),
        clear: () => setSearchTerm(""),
      }}
      deleteButtonProps={{
        onClick: () => setShowDeleteAlert(true),
        disabled: !selectedNoteIds.length,
      }}
      columnFilterProps={{
        columnFilters: [['title', {show: true, label: 'Title'}]],
        handleColumnFiltering: e => console.log(e),
      }}
  />**

Uncaught TypeError: Cannot read property 'replace' of undefined
    at a (layouts.js:2779)
    at layouts.js:40765
    at Array.map (<anonymous>)
    at A (layouts.js:40753)
    at renderWithHooks (react-dom.development.js:14972)
    at mountIndeterminateComponent (react-dom.development.js:17734)
    at beginWork (react-dom.development.js:18935)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3922)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3971)
    at invokeGuardedCallback (react-dom.development.js:4031)

react-dom.development.js:19959 The above error occurred in the <A> component:

    at A (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:62428:44)
    at div
    at div
    at ot (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:62377:17)
    at Notes (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:2858:73)
    at Route (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:166027:29)
    at Switch (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:166229:29)
    at div
    at div
    at Home
    at Route (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:166027:29)
    at PrivateRoute (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:1844:24)
    at Switch (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:166229:29)
    at Router (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:165662:30)
    at BrowserRouter (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:165150:35)
    at Main (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:3328:73)
    at UserProvider (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:3603:23)
    at AuthProvider (http://localhost:3000/packs/js/application-2e2efe6b00306d4ae58a.js:3501:23)
    at App

**Comment by edwinbbu** [comment]
Closing the issue since the prop passed is wrong to the subheader.
