### ISSUE TITLE
Fix Table key error

### ISSUE THREAD

**Issue by shreyansh-g24** [bigbinary/neeto-ui#784]
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `wc`. See https://fb.me/react-warning-keys for more information.
    in BodyRow (created by wc)
    at wc (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:12881:266300)
    at table
    at div
    at div
    at http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:12881:276533
    at div
    at el (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:12881:276671)
    at div
    at div
    at n (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:12881:296846)
    at div
    at Ph (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:12881:394715)
    at Rh (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:12881:402112)
    at div
    at div
    at http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:12952:66169
    at SessionsSearchPlayground (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:4214:84)
    at Route (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:166272:29)
    at Switch (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:166478:29)
    at div
    at Container (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:2782:23)
    at div
    at Router (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:165901:30)
    at BrowserRouter (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:165389:35)
    at Main (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:3793:19)
    at HoneyBadgerErrorBoundary (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:14640:5)
    at UserProvider (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:7304:23)
    at AuthProvider (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:7201:23)
    at App (http://spinkart.lvh.me:9020/packs/js/application-3a1f89a58605404a4a1d.js:1523:35)
```

**Comment by amaldinesh7** [comment]
@shreyansh-g24 is there a key named "id" in the data that you passed for rowData prop? if yes can you please share the code?

**Comment by shreyansh-g24** [comment]
@amaldinesh7 The code has since been updated and the error is no longer being thrown.

Yes the entire objects' array was being passed to `rowData` which also included id.
